# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subnet/protocols/pb/mock_protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='subnet/protocols/pb/mock_protocol.proto',
  package='mock_protocol.pb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'subnet/protocols/pb/mock_protocol.proto\x12\x10mock_protocol.pb\"\xb2\x01\n\x13MockProtocolMessage\x12K\n\x04type\x18\x01 \x02(\x0e\x32=.mock_protocol.pb.MockProtocolMessage.MockProtocolMessageType\x1a!\n\x04Peer\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\"+\n\x17MockProtocolMessageType\x12\x10\n\x0cTASK_REQUEST\x10\x00'
)



_MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE = _descriptor.EnumDescriptor(
  name='MockProtocolMessageType',
  full_name='mock_protocol.pb.MockProtocolMessage.MockProtocolMessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_REQUEST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=197,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE)


_MOCKPROTOCOLMESSAGE_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='mock_protocol.pb.MockProtocolMessage.Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mock_protocol.pb.MockProtocolMessage.Peer.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addrs', full_name='mock_protocol.pb.MockProtocolMessage.Peer.addrs', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=195,
)

_MOCKPROTOCOLMESSAGE = _descriptor.Descriptor(
  name='MockProtocolMessage',
  full_name='mock_protocol.pb.MockProtocolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mock_protocol.pb.MockProtocolMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MOCKPROTOCOLMESSAGE_PEER, ],
  enum_types=[
    _MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=240,
)

_MOCKPROTOCOLMESSAGE_PEER.containing_type = _MOCKPROTOCOLMESSAGE
_MOCKPROTOCOLMESSAGE.fields_by_name['type'].enum_type = _MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE
_MOCKPROTOCOLMESSAGE_MOCKPROTOCOLMESSAGETYPE.containing_type = _MOCKPROTOCOLMESSAGE
DESCRIPTOR.message_types_by_name['MockProtocolMessage'] = _MOCKPROTOCOLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MockProtocolMessage = _reflection.GeneratedProtocolMessageType('MockProtocolMessage', (_message.Message,), {

  'Peer' : _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
    'DESCRIPTOR' : _MOCKPROTOCOLMESSAGE_PEER,
    '__module__' : 'subnet.protocols.pb.mock_protocol_pb2'
    # @@protoc_insertion_point(class_scope:mock_protocol.pb.MockProtocolMessage.Peer)
    })
  ,
  'DESCRIPTOR' : _MOCKPROTOCOLMESSAGE,
  '__module__' : 'subnet.protocols.pb.mock_protocol_pb2'
  # @@protoc_insertion_point(class_scope:mock_protocol.pb.MockProtocolMessage)
  })
_sym_db.RegisterMessage(MockProtocolMessage)
_sym_db.RegisterMessage(MockProtocolMessage.Peer)


# @@protoc_insertion_point(module_scope)
