"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MockProtocolMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _MockProtocolMessageType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _MockProtocolMessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MockProtocolMessage._MockProtocolMessageType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TASK_REQUEST: MockProtocolMessage._MockProtocolMessageType.ValueType  # 0

    class MockProtocolMessageType(_MockProtocolMessageType, metaclass=_MockProtocolMessageTypeEnumTypeWrapper): ...
    TASK_REQUEST: MockProtocolMessage.MockProtocolMessageType.ValueType  # 0

    @typing.final
    class Peer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        ADDRS_FIELD_NUMBER: builtins.int
        id: builtins.bytes
        @property
        def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
        def __init__(
            self,
            *,
            id: builtins.bytes | None = ...,
            addrs: collections.abc.Iterable[builtins.bytes] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["id", b"id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["addrs", b"addrs", "id", b"id"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    type: Global___MockProtocolMessage.MockProtocolMessageType.ValueType
    def __init__(
        self,
        *,
        type: Global___MockProtocolMessage.MockProtocolMessageType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["type", b"type"]) -> None: ...

Global___MockProtocolMessage: typing_extensions.TypeAlias = MockProtocolMessage
